environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "4"
    - nodejs_version: "5"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set CI=true
  # - npm install -g npm@3.x-latest
  - npm install -g yarn --cache-min 999999999
  - set PATH=%APPDATA%\npm;%APPDATA%\yarn;%PATH%
  # - npm install --unsafe-perm
  # - npm prune
  - yarn
test_script:
  - node --version
  - yarn --version
  # npm script for windows test
  # - npm run test:win
  - yarn test:win
# GO_FAST
matrix:
  fast_finish: true
# we don't need the builds, we just need tests
build: off
